### ISSUE TITLE
Finalize domain name

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#1]
# Acceptance criteria
- [x]  Finalized Domain name 
- [x]  I have registered the domain name `namecheap.com`. 
- [x]  I have the necessary information regarding the domain names (eg. credentials, DNS info etc.). 
# Tasks 
- [x]  Discuss with D4D and committee members to finalize domain names. 
- [x]  Register Domain name
- [x]  Register domain name “womenindatanepal.com” and provide credentials to Open Knowledge Nepal.

**Comment by sagargg-zz** [comment]
@nikeshbalami  Could you ask for the necessary credentials. If it is  Namecheap,  you can ask to share the access. Share to email `info@sagarg.com.np`. 

<img width="1378" alt="Screen Shot 2021-02-19 at 8 58 38 AM" src="https://user-images.githubusercontent.com/11631101/108452476-abe99080-7290-11eb-9e8e-cb0448e3e4a4.png">

**Comment by nikeshbalami** [comment]
Thank you, will email the D4D team for the access.

**Comment by nikeshbalami** [comment]
@sagargg have you received the invite?

**Comment by sagargg-zz** [comment]
@nikeshbalami  I just received access to that domain.
