### ISSUE TITLE
Develop graphics that reflect committee goals adapting the branding

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/widnepal-web#10]
# Acceptance criteria

- [x] I have a graphic that reflects committee goals.

# Tasks 
- [x] Brainstorm how the committee goals can be displayed via the effective use of graphics.
- [x] Develop a couple of graphics and discuss them with committee members.
- [x] Finalize the graphics incorporating feedback.

**Comment by sagargg-zz** [comment]
@nikeshbalami  Could you clarify where those graphics can be used?  Do you mean the image on the homepage banner? (women with bar chart)

**Comment by nikeshbalami** [comment]
Yes, this issue is for the graphics which will be in the homepage banner.

**Comment by sagargg-zz** [comment]
Closing as DONE
