### ISSUE TITLE
Collect some women related visual statistics for display

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/widnepal-web#11]
# Acceptance criteria

- [x] I have statistics which are insightful and can be presented on a site.
- [x] I have verified the quality and source of the statistics.
- [x] I have provided the dev team with statistics.

# Tasks 
- [x] Research and collect some national statistics related to women and data.
- [x] Discuss with the dev team and brainstorm how it can be presented on a site.
- [x] Provide the dev team with presentation ideas and data.

# DOCS

- [x] Working docs containing statistics [here](https://docs.google.com/document/d/1UC6mjm02klEcDL7KXM2BP3-ijwN2-JtSTDh4VKXeA1Q/edit?usp=sharing).

**Comment by nikeshbalami** [comment]
I have collected some facts in the working docs. They were in the presentation slides uploaded on the old website.

**Comment by sagargg-zz** [comment]
@nikeshbalami great. Could you also select the best 5 facts?

**Comment by nikeshbalami** [comment]
Sure, will do that.

**Comment by sagargg-zz** [comment]
Closing as **DONE**.
