### ISSUE TITLE
Boilerplate setup of the nextjs  (Frontend)

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#12]
## Acceptance criteria
 - [x] I have a Minimal boilerplate setup of the next js application with a welcome home page.
 
## Tasks
- [x]  Write  nextjs  starter code  with welcome page.
-  [x] Update readme about how to run locally.

**Comment by sagargg-zz** [comment]
@arjun-gautam maybe we can use quick starter code.

**Comment by arjun-gautam** [comment]
Hey, @sagargg it is done

**Comment by sagargg-zz** [comment]
@arjun-gautam  Thanks.

**Comment by sagargg-zz** [comment]
@arjun-gautam  Not sure why we need to checkout in another branch  `git switch wordPress`. We could use the same `master` branch right.

**Comment by sagargg-zz** [comment]
@arjun-gautam  Review this PR: #13

**Comment by arjun-gautam** [comment]
@sagargg merge is complete. I am working on category based filter through graphQL. This is a part of boilerplate.

**Comment by arjun-gautam** [comment]
Added query with filter for all the pages. That's all for boilerplate part. But I am not closing this issue. @sagargg Is it okay to close this issue?

**Comment by arjun-gautam** [comment]
Should we add anything more? BTW, I have also updated the readme.md

**Comment by sagargg-zz** [comment]
@arjun-gautam  Yes, we can close this issue. Since the work is done as an acceptance creature. 
>  I have a Minimal boilerplate setup of the next js application with a welcome home page.
