### ISSUE TITLE
Custom post/page for resource and events.

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#18]
We also have an event and resource page. We need to store that related information on the backend, by default WordPress doesn't have that feature. 

# Acceptance criteria 
- [x] I can store event and resource  info on WordPress via admin UI

# Tasks
- [x] Do an analysis of how we can store data on WordPress for events and resources.
- [x]  Implement and test.

**Comment by sagargg-zz** [comment]
@arjun-gautam  Closing since it was already implemented.
