### ISSUE TITLE
Finalize color and font branding

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#2]
# Acceptance criteria
- [x]  I have reached out to the D4D and YUWA team to collect old branding materials.
- [x]  I have collected the logo and content of previous years
- [x]  I have the branding details which guide the use of color and fonts for the development process.

# Tasks 
- [x]  Reach out to the D4D and YUWA team to collect the branding details of the previous year.
- [x] Compile the details and finalize the color and font branding.

# DOCS

- Working docs [here](https://docs.google.com/document/d/1FGHoHpqoANjwk9_m6SNYem-53SmFKqew4bn2fUqRdhQ/edit?usp=sharing).

**Comment by sagargg-zz** [comment]
@nikeshbalami  Can we close this issue?

**Comment by nikeshbalami** [comment]
Not now, we will close this one; after the font is finalized.

**Comment by nikeshbalami** [comment]
A basic guideline for the logo, colors, and fonts has been finalized and documented here: https://docs.google.com/document/d/1FGHoHpqoANjwk9_m6SNYem-53SmFKqew4bn2fUqRdhQ/edit?usp=sharing

**Closing this issue.**
