### ISSUE TITLE
Playaround on the fonts

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#26]
# Acceptance
*  [x] I've shared a screenshot of the tested font and shared it with the team for input.

# Tasks
*  [x]  play around with the free font.
*  [x] Share screenshots with the team and collect inputs. 
*  [x] Update in branding docs after it finalized. 

// @nikeshbalami

**Comment by arjun-gautam** [comment]
@sagargg @nikeshbalami  How does this process go? Is it like me sharing you guys screenshots and you guys decide which fonts to use? In that case, comment below some fonts which you want to see in screenshots. I will provide you screenshots along with the name of fonts.

**Comment by sagargg-zz** [comment]
@arjun-gautam  Yes, You'll be sharing the screenshots.  First, you should try out some fonts and share screenshots whichever you liked then we also do the review. 

One is Kerala and it's pairing fonts.  
- https://fonts.google.com/specimen/Karla?preview.text_type=custom
- https://fonts.google.com/specimen/Karla?preview.text_type=custom#pairings

Another Spartan
- https://fonts.google.com/specimen/Spartan?preview.text_type=custom
- https://fonts.google.com/specimen/Spartan?preview.text_type=custom#pairings

**Note:** don't forget to try other variants on the font (eg. bolder, light, regular, etc.)

**Comment by sagargg-zz** [comment]
@arjun-gautam  can you change the typography close to this screenshot. 
Used two fonts here 
**Headers:** 
size: 30px
Font: ROBOTO
Color: rgb(64, 62, 62)

**paragraph/body:** 
size: 18px
Font: Nunito sans
Color: rgb(64, 62, 62)

![screencapture-localhost-3000-home-2021-02-22-10_28_31](https://user-images.githubusercontent.com/11631101/108663474-c0c85d00-74f8-11eb-9559-7aef343f733f.png)

```
@import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,200;0,300;0,400;0,600;0,700;1,200;1,300;1,400;1,600&family=Roboto:ital,wght@0,400;0,500;1,400&display=swap');
```
Fall back  font should be ` sans-serif`. 
```
  font-family: 'Nunito Sans', sans-serif;
font-family: 'Roboto', sans-serif; 
```

**Comment by arjun-gautam** [comment]
I made few screen shots and uploaded to Figma. Please provide some input. @sagargg @nikeshbalami

**Comment by arjun-gautam** [comment]
@sagargg Where is the branding docs?

**Comment by nikeshbalami** [comment]
Here is the branding docs: https://docs.google.com/document/d/1FGHoHpqoANjwk9_m6SNYem-53SmFKqew4bn2fUqRdhQ/edit?usp=sharing

I have already updated the details. We can close this issue now.

**Comment by arjun-gautam** [comment]
okay
