### ISSUE TITLE
Create a staging  live site

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#27]
Currently, there is no staging site and it is difficult to see what's done what's not done.  Whenever the latest change is made eg. new feature added/bug fixes I want to see that in live so, that i  can test, collect feedbacks and plan accordingly.  

# Acceptance 
* [x] I can browser the updated d website accessing URL eg. `wid-website.oknp.org`

# Task 
* [x] Sync with Sagar for the deployment. 
* [x] Deploy the project
* [x] Notify the team  providing staging url.

// @nikeshbalami
