### ISSUE TITLE
Replacing the 'In spotlight' section content  with blog post. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#28]
We found the on In spotlight section context, the implementation was, It should display the blog post instead of the event post. 

# Accepance 
* [x] I can see  the `in spotlight section content` in the homepage  replaced with event post

# Task
* [x]  Replace the event post with a blog post. ( necessary changes on code)
* [x]  Recent 5 posts or manually can be pinpoint post. (ever approach you can do. )
* [x] Test yourself to confirm it is working as expected. 

//cc @nikeshbalami

**Comment by arjun-gautam** [comment]
Closing with remark: Instead of recent 5 posts pinned posts are shown.
