### ISSUE TITLE
Collect necessary  information  regarding the conference website. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#29]
# Acceptace
 * [x]  I have all the information which are required to move forward on the conference website development. 

# Tasks
* [x]  Set a meeting with sagar for the discussion. 
* [x] Collect require information on docs. 
* [x] Add  other tasks after the sync. ( if any)

# DOCS

- Working docs which will have conference details [here](https://docs.google.com/document/d/18lMgzpZETJs4dHBJACqeI9CZ7eTTvQb-9C5FG_LE0Zw/edit?usp=sharing).

**Comment by nikeshbalami** [comment]
Added the link for the working docs, where the committee members are working to finalize the conference structure.
cc @sagargg

**Comment by nikeshbalami** [comment]
@arjun-gautam @sagargg Guys, I have updated the link of working docs. That doc will contain all necessary information required for the conference website.

**Comment by arjun-gautam** [comment]
@nikeshbalami @sagargg All the content in the following doc link is up to date.
https://docs.google.com/document/d/18lMgzpZETJs4dHBJACqeI9CZ7eTTvQb-9C5FG_LE0Zw/edit

**Comment by arjun-gautam** [comment]
Mistakely "close with comment"ed the issue. haha. reopened it.

**Comment by nikeshbalami** [comment]
New details has been updated in the working docs docs. cc @arjun-gautam @sagargg

**Comment by arjun-gautam** [comment]
@nikeshbalami noted. I will update it

**Comment by arjun-gautam** [comment]
@nikeshbalami  updated it

**Comment by sagargg-zz** [comment]
@nikeshbalami  anything remaining to update. Please review the content section.

**Comment by nikeshbalami** [comment]
The conference page looks good.

**Closing the issue.**
