### ISSUE TITLE
Curate content related to committee mission, visions and thematic areas

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#3]
# Acceptance criteria

- [x]  I have the documents which contain details related to the committee mission, visions, and thematic areas.
- [x]  I have provided all relevant content to the developer.

# Tasks 

- [x] Reach out and discuss with a committee member to curate the content
- [x] Provide the curated content to the development team

# Docs

- [x] Working docs containing content [[here](https://docs.google.com/document/d/1m0JUtb7St2-cCQZEczHciNWK0TGqUb73kNhlpjA5N0A/edit?usp=sharing)]

**Comment by sagargg-zz** [comment]
@nikeshbalami  Could you share the status of this. It would be great if you can share it soon cuz it is blocking the design work.  // cc @arjun-gautam

**Comment by nikeshbalami** [comment]
Highlighted this as one of the major backlogs in today's meeting [FEB 16], might receive the content by tonight.

**Comment by nikeshbalami** [comment]
The content has been received. cc @arjun-gautam @sagargg

**Comment by sagargg-zz** [comment]
CLOSING this. We've already received the content.
