### ISSUE TITLE
Add sidebar on all pages. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#31]
# Acceptance criteria 
* [x]  I can see the quote image, and facts sidebar on all page as similar figma design. Also, it is admin configurable. 

# Tasks
* [x] Add e configurable quote image on the sidebar as similar to figma design. 
* [x]  Add selected 5 facts on the sidebar as similar to the figma design.  [You can find the facts on doc](https://github.com/okfnepal/widnepal-web/issues/11)

Related: #37 

// cc @nikeshbalami
