### ISSUE TITLE
Contact us form 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#32]
# Acceptance criteria 
* [x] I can see the contact form on the contact us page as similar to the design.  
* [x] When i submit the form, the admin can receive the summited form information in the email inbox.

# Tasks
* [x]  Do Analysis submit form can be sent an email to the admin.  (Maybe require to add/wirte plugins)
* [x] Check if the already plugin exists for that. 
    * [ ] If not,  how to capture submit form payload on wordpress and send email using email hook function on WordPress. 

// @nikeshbalami

**Comment by sagargg-zz** [comment]
@arjun-gautam  you can take a ref. example from branch `contact-form` for sending contact payload to email.  I've already sent you an email/password detail for testing on chat.

**Comment by sagargg-zz** [comment]
Not tested yet but we can test later along with final feedback/touch. 
Closing as **DONE**.
