### ISSUE TITLE
Add sidebar section on pages as per figma design. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#37]
# Acceptance criteria 
- [x] I can see the sidebar section on pages as similar to Figma design. 
- [x]   I can add/edit/change quotes image on sidebar similar to Figma design.
- [x]  I can add/edit/change the facts shown on the sidebar via admin UI. 

# Tasks 
- [x]  Do the necessary analysis and implement (coding). 
- [x] notify/ask team to test it.

**Comment by sagargg-zz** [comment]
@arjun-gautam  use these image and quote for the sidebar quote image.   I've already updated on Figma design, please take a ref.  from there.  
```
The world cannot be understood without numbers and it cannot be understood with numbers alone.
-  Dr. Hans Rosling, Factfulness
```

![40294274331_058ff4fe3f_b](https://user-images.githubusercontent.com/11631101/109391433-24121f00-793f-11eb-9269-1e2e6817a6a3.jpeg)


**Note:** This image is license under the public domain.  cc @nikeshbalami

**Comment by sagargg-zz** [comment]
@arjun-gautam  We will be featuring the top best 5 facts on the sidebar.  Please find the facts from doc mentioned on this issue #31. 
 **Note** we only featuring 5 facts on the sidebar so, please add 5 facts items from the top of the doc. 
 
 cc @nikeshbalami

**Comment by sagargg-zz** [comment]
Closing as DONE
