### ISSUE TITLE
Collect feedbacks on features and design. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#39]
# Tasks

- [x] Go through all features of the stagging site
- [x] Collect feedbacks in the working docs

# Items 
- [x]  Currently, on the Homepage, we have the Women In Data logo, where the text is written in white color and the background d is blue. But when we go to other pages where the background is white for example "Resources" that text doesn't display. So, on the other page (beside the homepage)  logo should be replaced with blue text. 
- [x] Redirect to Homepage when clicking on the logo. Currently, we can't click the logo. Make sure it's clickable and when clicked redirect it to the Homepage.
- [x] Increase the size of Banner by some portion - current size is a little small, increase in height.
               <img width="300" alt="Screen Shot 2021-03-08 at 11 39 55 AM" src="https://user-images.githubusercontent.com/11631101/110280698-5e488400-8003-11eb-8033-4c052383a0da.png">
- [x] Replace "Why Should I Take Part?" text with "Thematic Areas" in the Banner - and forward it to the thematic areas page.
- [x] Add 's' in the Member Organization [Member Organizations] and update the WiSTEM png logo.
- [x] Implement "Twitter features" - https://github.com/okfnepal/widnepal-web/issues/46 
- [x] Add more gap between text and "Get Involved" button.
    <img width="1436" alt="Screen Shot 2021-03-08 at 11 44 01 AM" src="https://user-images.githubusercontent.com/11631101/110280874-ad8eb480-8003-11eb-9a4d-dcf5852d8675.png">

- [x] Implement "Footer features" - https://github.com/okfnepal/widnepal-web/issues/44 
- [x] Manage the URL of Thematic Areas page - currently, it shows this url: http://wid.oknp.org/about/other?page=Thematic%20Areas 
- [x] In the "Upcoming Event" page, the event date has been cropped into half probably because of the sidebar. 
   <img width="500" alt="Screen Shot 2021-03-08 at 11 45 53 AM" src="https://user-images.githubusercontent.com/11631101/110280982-e62e8e00-8003-11eb-858e-98b9d721c4ae.png">
- [x] Add extra padding on page breadcrumbs
    <img width="300" alt="Screen Shot 2021-03-08 at 11 50 32 AM" src="https://user-images.githubusercontent.com/11631101/110281267-7ec50e00-8004-11eb-9cce-e235875619cf.png">
- [x] Add extra  space on blog 
    <img width="400" alt="Screen Shot 2021-03-08 at 11 51 54 AM" src="https://user-images.githubusercontent.com/11631101/110281428-d499b600-8004-11eb-8584-1b14c953c51d.png">
    - [x]  on footer as well.
        <img width="400" alt="Screen Shot 2021-03-08 at 11 53 16 AM" src="https://user-images.githubusercontent.com/11631101/110281491-f3984800-8004-11eb-9260-07c5e41a0b2e.png">
- [x]  Add extra gap on between the page and sidebar. 
    <img width="400" alt="Screen Shot 2021-03-08 at 11 56 35 AM" src="https://user-images.githubusercontent.com/11631101/110281744-643f6480-8005-11eb-9c81-1e7a9a792b5a.png">
- [x] try light/dark blue on clipart on homepage banner.

**Comment by nikeshbalami** [comment]
Guys, I have collected some basic to-do. We are good to go live once we are done with these lists: https://docs.google.com/document/d/1qmm4q3ptfmlJ_AdnORXpdppuKEAzkgwEDzn9TMfPqbo/edit?usp=sharing

cc @arjun-gautam @sagargg

**Comment by arjun-gautam** [comment]
As suggested in the doc, I changed the logo icon to Fav style icon

**Comment by arjun-gautam** [comment]
Clicking on logo will redirect to home

**Comment by arjun-gautam** [comment]
@nikeshbalami @sagargg And all the rest completed besides the twitter

**Comment by nikeshbalami** [comment]
Thank you @arjun-gautam, it looks much better now. We still have some cleaning left, will add those into the issue.

**Comment by nikeshbalami** [comment]
- [x] Arrange member's logo in alphabetical order.

![image](https://user-images.githubusercontent.com/3656268/110723995-1a40c380-823d-11eb-9a83-ec193eb35ab0.png)

- [x] Reduce the font size of the copyright info.

![image](https://user-images.githubusercontent.com/3656268/110724017-22006800-823d-11eb-85fb-52cb94839f6d.png)

- [x] Create a master author in the name of "Women In Data" and pass the authorship to that name.

![image](https://user-images.githubusercontent.com/3656268/110724040-29277600-823d-11eb-99ab-a944458fe1e8.png)

cc @arjun-gautam

**Comment by arjun-gautam** [comment]
All tasks are completed. You may review and close this.

**Comment by nikeshbalami** [comment]
All the tentative feedbacks has been successfully implemented. Will open a new issue, if we receive feedback from the committee members.

**Closing This**

Thank @arjun-gautam @sagargg
