### ISSUE TITLE
Collect logos and bio of committee member, advisors and community groups

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#4]
# Acceptance criteria
- [x]  I have the latest updated logos and bio of all members, advisors, and community groups.
- [x]  Designer/developer received  all logos and bio.

# Tasks 
 - [x] Contact partners and member organizations asking SVG logos and a short bio.
- [x] Provide a logo and bio to the designer/developer team.

# Docs
- [x] Upload the logo [[here](https://drive.google.com/drive/folders/1BcHx5OrSU6XI8t1r942XAIZAnRei7x-w?usp=sharing)]
- [x] Submit the short bio [[here](https://docs.google.com/document/d/1MkE72Sl8q52PUj7ag3kSI0nidONX9n21PfGDDd94DJo/edit?usp=sharing)]

**Comment by nikeshbalami** [comment]
Had asked the committee member to submit respective details.

**Comment by nikeshbalami** [comment]
The logo and bio of all the committee members and supporters have been received. cc @arjun-gautam @sagargg

**Comment by sagargg-zz** [comment]
@nikeshbalami  I see few things are missing there. Email, social links, website links.  Also had confusion, not sure which are advisory orgs and which are member orgs.

**Comment by nikeshbalami** [comment]
The details of the committee members have been collected. Let's not have the page for advisory org for this phase, because the organization is yet to be identified.

**Comment by sagargg-zz** [comment]
closing as **DONE**.
