### ISSUE TITLE
Collect done and not done items. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#40]
# Acceptance criteria  
- [ ] I have a list of items that already done need to be done.
# Tasks 
- [x] go through the requriments docs.
- [x]  List out a checklist of done and undone items. 
 # Collected Here:
 https://docs.google.com/document/d/1qmm4q3ptfmlJ_AdnORXpdppuKEAzkgwEDzn9TMfPqbo/edit#

**Comment by arjun-gautam** [comment]
@sagargg How is this issue going?

**Comment by sagargg-zz** [comment]
@arjun-gautam  will do after we finished the feedback/enhancement issues.

**Comment by sagargg-zz** [comment]
@arjun-gautam  @nikeshbalami I've collected items on the doc. Feel free to updated.

**Comment by sagargg-zz** [comment]
Closing as Done
