### ISSUE TITLE
Collect slogan/quotes that reflect committee goals

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#5]
# Acceptance criteria
- [x]  I have at least one or two quotes that can be adapted and use.
- [x]  Provided quote to the designer/dev team.
# Tasks 
- [x]  Brainstorm and discuss with committee members regarding what quotes can be used.
- [x]  Provide the quote to the dev team.

# DOCS

- [ ] Working docs containing slogan/quotes [here](https://docs.google.com/document/d/1mmA-7aBHyhOqATHqL1MpblcIyRCikcADVpe0EMf2xpc/edit?usp=sharing).

**Comment by nikeshbalami** [comment]
Have curated a few of the quotes in the working docs. Will those types of quotes work?? cc @arjun-gautam @sagargg

**Comment by sagargg-zz** [comment]
@nikeshbalami  it will great if that covers two scope data and women.   I guess this will work on the sidebar image.

**Comment by sagargg-zz** [comment]
**Related**: #37
@nikeshbalami  @arjun-gautam We've finalized the quotes, however, it doesn't reflect committee goals directly but we'll use that so closing as **DONE**.
