### ISSUE TITLE
Prepare the report and technical guidebook

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/widnepal-web#52]
As part of the contract with D4D, compile and prepare the report including the technical guide.

## TODO

- [x] Finalize the draft structure of the document
- [x] Share the format with the team
- [x] Compile the content, important details and screenshots
- [x] Review and finalize

## Working Docs

- Working docs link [here](https://docs.google.com/document/d/1yVDKRFHsO7d6ctsqwDnxwXYuIhF_bWUWk5BFChblms8/edit?usp=sharing).

**Comment by arjun-gautam** [comment]
@nikeshbalami @sagargg Guys, mailey technical guide complete garey. Herera feedback garum na hai. K changes haru garnu parchha hola aru?

**Comment by nikeshbalami** [comment]
Thank you @arjun-gautam, it looks good.

Since now we have both report and guidebook prepared. _Closing the issue_
