### ISSUE TITLE
Create page mockups incorporating available requirements

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#6]
# Acceptance criteria
- [x]  I have the design mockups ready on all pages.
- [x]  I have submitted mockups to the developer team.

# Tasks 
- [x]  Design mockup Incorporating all user stories.
- [x]  Discuss and take feedback.
- [x]  Submit the mockups to the ~~developer team~~.

**Comment by sagargg-zz** [comment]
@arjun-gautam  please find the XD file of the design mockup. 
[WID.xd.zip](https://github.com/okfnepal/widnepal-web/files/5939356/WID.xd.zip)

**Comment by sagargg-zz** [comment]
Also sharing here three js particles animation. 
[three.zip](https://github.com/okfnepal/widnepal-web/files/5939393/three.zip)

**Comment by arjun-gautam** [comment]
Thanks bro. I will go through the resources

**Comment by arjun-gautam** [comment]
Hey, today I am planning to add the animation code in the home page. The above three.zip file.

**Comment by sagargg-zz** [comment]
Already **DONE**
