### ISSUE TITLE
Collect potential image that can be useful in website (licenced under CC0 or CC BY-SA)

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/widnepal-web#7]
# Acceptance criteria

- [x] I have at least two images that can be used in the design.

# Tasks 

- [x] Brainstorm the tentative types of images, which will fit as per design perspective.
- [x] Collect good open licensed images that represent women and data.

**Comment by sagargg-zz** [comment]
@nikeshbalami  we still need an image on the home page. ( I guess images from the last conference will be good.)

**Comment by nikeshbalami** [comment]
Some of the selected images from last year conference and side events have been collected here: https://drive.google.com/drive/folders/17izagPd8QfQtf19vRI_OIQeRJd4tLOQH?usp=sharing

**Comment by sagargg-zz** [comment]
closing as **DONE**.
