### ISSUE TITLE
Development setup wordpress in docker composer. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#8]
# Acceptance criteria 
- [x] I have a development docker setup of WordPress providing (REST?/GRAPH?) API.

# Tasks
-  [x] Create docker composer writing docker configuration. 
-  [x] Integrate REST/graphQL feature (may be required to install the plugins)

**Comment by sagargg-zz** [comment]
**ref.** follow the reference if haven't  done this before. https://docs.docker.com/compose/wordpress/
Also, let me know if you need help with this.

**Comment by sagargg-zz** [comment]
**Already done** : commit https://github.com/okfnepal/widnepal-web/commit/5c5b5bb8a4aab0cffff589cbdd87a8ef1e552cc5

**Comment by sagargg-zz** [comment]
@arjun-gautam  In order to check the acceptance criteria, I'm still not clear about which API we will be using graphSQL/REST on the project? Not sure but I think  REST API  will come with generic WordPress but Graphsql may need an extra plugin.

**Comment by sagargg-zz** [comment]
Synced with Arjun, agree to user graphQL.

**Comment by sagargg-zz** [comment]
Closing as **Done**.
