### ISSUE TITLE
Setup boilerplate of nextjs appilication 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#9]
# Acceptance criteria 
- [ ]  I have a Minimal boilerplate setup of the next js application with a welcome home page. 
- [ ]  I can run the Nextjs application with the docker compose command.  

# Tasks
@arjun-gautam  please add relevant tasks. 
- [ ] Expose/bind `/src` folder with  docker container.

**Comment by sagargg-zz** [comment]
@arjun-gautam  Maybe we don't need to add it as separate docker container service since it just use node dependency and Wordpress API. I think it will  easy to debug with direct installation so, closing it for  now.
